[versions]
pre-commit-githooks = "2.0.25"
foojay-resolver-convention = "1.0.0"

[plugins]
gitSemVer = {id = "org.danilopianini.gradle-pre-commit-git-hooks", version.ref = "pre-commit-githooks"}
foojayResolver = {id="org.gradle.toolchains.foojay-resolver-convention", version.ref="foojay-resolver-convention"}